function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 10-Dec-2012 21:42:20

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0698254364089776 0.0812379110251451 0.870324189526185 0.866537717601548],...
    'ColorOrder',[1 1 0;1 0 1;0 1 1;1 0 0;0 1 0;0 0 1]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1.9 5]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create xlabel
xlabel('Time[sec]');

% Create ylabel
ylabel({'Connecting Force fConn[N]'},'Interpreter','none');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Tag','Run #1 - data1','LineStyle','--','Color',[1 0 0],...
    'DisplayName','fConn1');
set(plot1(2),'Tag','Run #1 - data2','LineWidth',1,...
    'Color',[0 0.498039215803146 0],...
    'DisplayName','fConn2');
set(plot1(3),'Tag','Run #1 - data3','LineStyle','-.',...
    'Color',[0 0.749019622802734 0.749019622802734],...
    'DisplayName','fConn3');
set(plot1(4),'LineStyle',':','Color',[0 0 1],'DisplayName','fConn4');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[0.749019622802734 0 0.749019622802734],...
    'ZColor',[1 1 1],...
    'YColor',[0.749019622802734 0 0.749019622802734],...
    'XColor',[0.749019622802734 0 0.749019622802734]);

