function createfigure6(X1, YMatrix1)
%CREATEFIGURE6(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 28-Jan-2013 03:27:06

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'LineWidth',2,'LineStyle','--','Color',[1 0 0],...
    'DisplayName','Ideal Stiffness 200 [Nm/rad]');
set(plot1(2),'MarkerSize',8,'Marker','*','LineStyle','none',...
    'DisplayName','Measured Displacement');

% Create xlabel
xlabel('Object Rotation Error [quaternion]');

% Create ylabel
ylabel('Torque [Nm]');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.618397689016651 0.449014803450283 0.264563106796117 0.06158357771261]);

