function createfigure4(X1, Y1)
%CREATEFIGURE4(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 10-Jan-2013 05:40:45

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 130]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'MarkerSize',10,'Marker','square','LineWidth',1.5,...
    'LineStyle','--',...
    'Color',[1 0 0],...
    'DisplayName','Translational Stiffness K');

% Create xlabel
xlabel('Object Position Error [m]');

% Create ylabel
ylabel('Force [N]');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.701921501147164 0.558381088825213 0.146181579809898 0.0334288443170965]);

