function createfigure5(X1, Y1)
%CREATEFIGURE5(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 10-Jan-2013 18:57:39

% Create figure
figure1 = figure('PaperType','a4letter',...
    'PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'MarkerSize',10,'Marker','square','LineWidth',1.5,...
    'LineStyle','--',...
    'Color',[1 0 0],...
    'DisplayName','Rotational Stiffness K');

% Create xlabel
xlabel('Object Rotation Error [rad]');

% Create ylabel
ylabel('Torque [Nm]');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.701921501147164 0.558476327697911 0.146181579809898 0.0332383665716999]);

